In [7]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
#X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
X = np.array([[1, 3, 2, 1, 2, 1, 1], [7, 0, 2, 1, 0, 0, 1], [1, 7, 0, 0, 2, 0, 1], [1, 0, 0, 0, 7, 1, 2], [0, 2, 0, 0, 7, 1, 1]])
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(X)
print "indices=\n", indices
print "\ndistances=\n", distances

indices=
[[0 2]
 [1 0]
 [2 0]
 [3 4]
 [4 3]]

distances=
[[ 0.          4.69041576]
 [ 0.          7.07106781]
 [ 0.          4.69041576]
 [ 0.          2.44948974]
 [ 0.          2.44948974]]


The indices result above list the index of the nearest neighbour for each item.

In [9]:
X[2]

array([1, 7, 0, 0, 2, 0, 1])

In [11]:
print indices[0], type(indices[0])

[0 2] <type 'numpy.ndarray'>


In [12]:
indices[0][1]

2

In [14]:
print "answer to Q2 = ", X[indices[0][1]]

answer to Q2 =  [1 7 0 0 2 0 1]
